from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum
from datetime import datetime
import uuid


class CaseType(str, Enum):
    """Classification of DFIR investigation types."""
    IP_THEFT = "ip_theft"
    MALWARE = "malware"
    RANSOMWARE = "ransomware"
    INSIDER_THREAT = "insider_threat"
    INCIDENT_RESPONSE = "incident_response"
    UNKNOWN = "unknown"


class EvidenceType(str, Enum):
    """Types of forensic evidence the platform can process."""
    MEMORY_IMAGE = "memory_image"
    DISK_IMAGE = "disk_image"
    EVTX_FILE = "evtx_file"
    REGISTRY_HIVE = "registry_hive"
    PREFETCH_DIR = "prefetch_dir"
    PCAP = "pcap"
    TRIAGE_PACKAGE = "triage_package"


class EvidenceItem(BaseModel):
    """A single piece of forensic evidence discovered during intake."""
    path: str
    evidence_type: EvidenceType
    size_bytes: int = 0
    verified: bool = False
    description: str = ""


class Objective(BaseModel):
    """A single investigation objective that must be satisfied."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    description: str
    satisfied: bool = False
    supporting_findings: List[str] = []


class PhaseStatus(str, Enum):
    """Execution status of an investigation phase."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class Phase(BaseModel):
    """A logical grouping of capabilities that form one investigation step."""
    id: str
    name: str
    description: str
    capabilities: List[str]
    status: PhaseStatus = PhaseStatus.PENDING
    depends_on: List[str] = []
    results_summary: str = ""


class QueueItem(BaseModel):
    """A single executable action in the investigation queue."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    capability: str
    args: Dict[str, Any] = {}
    phase_id: str
    priority: int = 5
    status: PhaseStatus = PhaseStatus.PENDING
    result_key: Optional[str] = None
    retry_count: int = 0
    max_retries: int = 2
    error_message: str = ""
    started_at: Optional[str] = None
    completed_at: Optional[str] = None


class InvestigationPlan(BaseModel):
    """The complete investigation plan generated by the Planner."""
    case_id: str = Field(default_factory=lambda: f"DFIR-{datetime.now().strftime('%Y%m%d-%H%M%S')}")
    case_type: CaseType = CaseType.UNKNOWN
    description: str = ""
    evidence: List[EvidenceItem] = []
    objectives: List[Objective] = []
    phases: List[Phase] = []
    queue: List[QueueItem] = []
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())


class InvestigationStatus(str, Enum):
    """Top-level status of an investigation."""
    PLANNING = "planning"
    AWAITING_APPROVAL = "awaiting_approval"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"


class InvestigationState(BaseModel):
    """Persistent state tracking for a running investigation."""
    case_id: str
    status: InvestigationStatus = InvestigationStatus.PLANNING
    current_phase: Optional[str] = None
    completed_capabilities: List[str] = []
    findings_count: int = 0
    iterations: int = 0
    max_iterations: int = 50
    errors: List[str] = []
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    last_watchman_verdict: Optional[Dict[str, Any]] = None
